### ISSUE TITLE
NBomber Csharp HttpStep/Http seems to be missing methods

### ISSUE THREAD

**Issue by lippsm** [PragmaticFlow/NBomber.Http#10]
I was trying to get started writing load tests using NBomber.Http in Csharp.  I downloaded the requisite packages (version 0.13.0). When I tried writing my first test based on the example csharp files I noticed the following: 
HttpStep has no Create method, only CreateRequest.
![image](https://user-images.githubusercontent.com/24718579/64029836-5c029100-cb13-11e9-9f17-5f55d3f0b718.png)

Also, it looks like NBomber.Http.CSharp does not have access to the Http object, as my IDE wanted to pull in and use System.Net.WebRequestMethods, which had no 'CreateRequest' method.

Then there's the 'nice to have': Is there a way, or should there be a way to provide cookies for a call?

I really like the way this project looks to be shaping up, and hope this helps!

**Comment by AntyaDev** [comment]
Hi @lippsm 
Thank you for your feedback. For now, NBomber.Http provides you a very static way to define a test without injecting any dynamic behavior. I think on Monday I will release a new version which will provide dynamic access to HttpReqeustMessage and then you can modify it as you want. 
Regarding set your custom Cookies - you can use .WithHeader("Cookie", "name=value")

**Comment by lippsm** [comment]
Thanks for the quick response! I look forward to checking out the update on
Monday.

**Comment by double-reinbows** [comment]
I also need to use the "CreateFromResponse" API so I can create a scenario which has an initial step to obtain JSON Web Token (JWT). Unfortunately,j this seems to be missing

**Comment by AntyaDev** [comment]
Hi @lippsm, @double-reinbows  
I have published a beta version of NBomber.Http 0.14.0
Now you can generate dynamic requests 
See examples:

https://github.com/PragmaticFlow/NBomber.Http/blob/dev/examples/NBomber.Http.CSharp/SimpleExample.cs

https://github.com/PragmaticFlow/NBomber.Http/blob/dev/examples/NBomber.Http.CSharp/SequentialSteps.cs

**Comment by double-reinbows** [comment]
thanks @AntyaDev ! I tried `dotnet add package NBomber.Http -v 0.14.0` but got package not found so I tried the nearest version which is `0.14.0-beta2`. I also updated NBomber to 0.14.0-beta

```$ dotnet list package
Project 'Stress Test' has the following package references
   [netcoreapp2.2]:
   Top-level Package               Requested      Resolved
   > Microsoft.NETCore.App   (A)   [2.2.0, )      2.2.0
   > NBomber                       0.14.0-beta    0.14.0-beta
   > NBomber.Http                  0.14.0-beta2   0.14.0-beta2

(A) : Auto-referenced package.```

**Comment by AntyaDev** [comment]
fixed
