### ISSUE TITLE
How to send "form-data" or "x-www-form-urlencoded" in the request body?

### ISSUE THREAD

**Issue by rei-gun** [PragmaticFlow/NBomber.Http#11]
From the examples I could only find JSON body...

**Comment by AntyaDev** [comment]
Hi @double-reinbows 
I suppose you want to send POST request with some JSON payload?
Here is an example:

var step = HttpStep.Create("simple step", async (context) =>
                Http.CreateRequest("POST", "https://yourwebsite/test")
                       .WithBody(new StringContent("{ some JSON }", Encoding.UTF8, "application/json"))
check

**Comment by rei-gun** [comment]
Yup this works, thanks!
