### ISSUE TITLE
Support for .Net Framework 4.x dropped in version 0.14

### ISSUE THREAD

**Issue by andrewharry** [PragmaticFlow/NBomber.Http#13]
Hi Antya,

Thanks for great library for load testing in C#
I just tried to upgrade from 0.13 - but couldn't

> You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework

Any chance this is just an oversight?

**Comment by AntyaDev** [comment]
Hi @andrewharry 
Thanks for a good catch, I probably did this manually and forgot to undo.
I have published 0.14.1 with netstandard2.0 support.
Can you try this one?

**Comment by andrewharry** [comment]
No...  Thank you for providing an excellent tool!
