### ISSUE TITLE
Getting Failures on simple example

### ISSUE THREAD

**Issue by andrewharry** [PragmaticFlow/NBomber.Http#14]
```
// SimpleScenario Class

var step = HttpStep.Create("simple step", async (context) =>
    Http.CreateRequest("GET", "https://gitter.im").WithHeader("Accept", "text/html"));

return ScenarioBuilder.CreateScenario("Simple", step);

// Main Class

var scenarios = new[] {
     SimpleScenario.GetScenario()
};

NBomberRunner
      .RegisterScenarios(scenarios)
     .LoadConfig("config.json")
     .RunInConsole();
```

When I run this with the following config it only reports failures

```
{
  "ScenarioName": "Simple",
  "WarmUpDuration": "00:00:00",
  "Duration": "00:00:10",
  "ConcurrentCopies": 1,
  "ThreadCount": 1
}
```

```
+----------------------------+------------------------------------------+
| step                       | details                                  |
+----------------------------+------------------------------------------+
| - name                     | Simple                              |
+----------------------------+------------------------------------------+
| - request count            | all = 15433 | OK = 0 | failed = 15433    |
+----------------------------+------------------------------------------+
| - response time            | RPS = 0 | min = 0 | mean = 0 | max = 0   |
+----------------------------+------------------------------------------+
| - response time percentile | 50% = 0 | 75% = 0 | 95% = 0 | StdDev = 0 |
+----------------------------+------------------------------------------+
| - data transfer            | min = - | mean = - | max = - | all = -   |
+----------------------------+------------------------------------------+
```

**Comment by andrewharry** [comment]
I have tried various urls and get the same issue.  I will check to see if there is more information in the logs

**Comment by AntyaDev** [comment]
Hi @andrewharry 
First, you don't need this

```csharp
var scenarios = new[] {
     SimpleScenario.GetScenario()
};
```

if you want to register several scenarios to run them in parallel just use this:
```csharp
NBomberRunner
      .RegisterScenarios(scenario1, scenario2, scenario3)
```

I run the same example and got this:

```csharp
var step = HttpStep.Create("simple step", async (context) =>
                     Http.CreateRequest("GET", "https://gitter.im")
                            .WithHeader("Accept", "text/html")
);

var scenario = ScenarioBuilder.CreateScenario("test_gitter", step);

NBomberRunner.RegisterScenarios(scenario)
    .LoadConfig("config.json")
    .RunInConsole();
```
my config:
```json
{
  "GlobalSettings": {
    "ScenariosSettings": [
      {
        "ScenarioName": "test_gitter",
        "WarmUpDuration": "00:00:00",
        "Duration": "00:00:10",
        "ConcurrentCopies": 1
      }
    ]   
  }  
}
```

[14:12:54 INF] scenario: 'test_gitter', duration: '00:00:10', RPS: '7', concurrent Copies: '1'
+----------------------------+---------------------------------------------------------------+
| step                       | details                                                       |
+----------------------------+---------------------------------------------------------------+
| - name                     | simple step                                                   |
+----------------------------+---------------------------------------------------------------+
| - request count            | all = 70 | OK = 70 | failed = 0                               |
+----------------------------+---------------------------------------------------------------+
| - response time            | RPS = 7 | min = 122 | mean = 141 | max = 706                  |
+----------------------------+---------------------------------------------------------------+
| - response time percentile | 50% = 130 | 75% = 132 | 95% = 137 | StdDev = 74               |
+----------------------------+---------------------------------------------------------------+
| - data transfer            | min = 30.13Kb | mean = 30.13Kb | max = 30.32Kb | all = 2.06MB |
+----------------------------+---------------------------------------------------------------+


Check that you have internet connection
