### ISSUE TITLE
Support for FeedData API

### ISSUE THREAD

**Issue by diegosps** [PragmaticFlow/NBomber.Http#19]
Hello, I just discovered this project now and I'm already using it to do some load test.
Seems great so far! Thanks.

Reading the issues on the main repo, I saw that you published a beta version with Data feed support. It looks very comprehensive, however it looks to be restricted to the mains Step class.

Do you have any plans to extend the HttStep with this functionality?
Ty

**Comment by AntyaDev** [comment]
Hi @diegosps 
Yes I am adding it now.
Will publish it soon.

**Comment by AntyaDev** [comment]
https://github.com/PragmaticFlow/NBomber.Http/commit/8f9a36fa890f2889d361493ee41acdef01f288c4
https://github.com/PragmaticFlow/NBomber.Http/commit/e2587d8762ece27620b6edd5c806f88279ee1c33
