### ISSUE TITLE
The documentation link is broken

### ISSUE THREAD

**Issue by OcasoProtal** [PragmaticFlow/NBomber.Http#27]
Currently the documentation link in README.md points to [https://nbomber.com/docs/plugins-http](https://nbomber.com/docs/plugins-http). Opening that URL will only give you a 404 not found.

**Comment by RoyalScribblz** [comment]
[https://nbomber.com/docs/protocols/http](https://nbomber.com/docs/protocols/http) believe this is the new one for people looking for it

**Comment by AntyaDev** [comment]
thanks, @OcasoProtal , @RoyalScribblz 
fixed
