### ISSUE TITLE
WithJsonBody method adds the wrong headers

### ISSUE THREAD

**Issue by vladdex** [PragmaticFlow/NBomber.Http#30]
<img width="803" alt="image" src="https://github.com/user-attachments/assets/f99e1361-0e43-400e-bf74-25c4e04eaa04">
This is how the official documentation specifies to use the .WithJsonBody method but using this will result in a request with the wrong headers.
The request should add a "Content-Type: application/json" header not the Accept header (which specifies the accepted response).
Using the WithJsonBody method now to do a post will result in an "UnsupportedMediaType" response.
<img width="880" alt="image" src="https://github.com/user-attachments/assets/117409bd-f7eb-42f4-b3cc-9db7ee754e45">
<img width="1163" alt="image" src="https://github.com/user-attachments/assets/5f1da337-639a-4c78-a0f9-8af2f132ea97">

**Comment by AntyaDev** [comment]
Hi @vladdex 
Thank you for this finding..
Will fix it now.

**Comment by AntyaDev** [comment]
Hi @vladdex 
Could you please try
https://www.nuget.org/packages/NBomber.Http/5.1.1

**Comment by vladdex** [comment]
Hi @AntyaDev , this still doesn't work. The content headers are still Byte array:
using `WithJsonBody()`
<img width="922" alt="image" src="https://github.com/user-attachments/assets/afa51cfa-9239-44a6-a6a3-8356fd29a71f">

using `WithBody()`
![image](https://github.com/user-attachments/assets/44ac6a1e-1a2d-49d2-81da-310c472cb08d)

Later Edit:
Looking at the code I think this should be StringContent instead of ByteArrayContent
<img width="721" alt="image" src="https://github.com/user-attachments/assets/83675d02-fa36-4401-9922-71bba8a3af04">

**Comment by AntyaDev** [comment]
@vladdex Please try 5.1.2
https://www.nuget.org/packages/NBomber.Http/5.1.2

**Comment by vladdex** [comment]
@AntyaDev working as expected. Thank you.
